/**
 * 浏览器调试用 Mock 目录数据（与 seeds 对齐的展示形状）。
 * 仅在无 WebView2 宿主时由 mockHost 使用。
 */
import type { CatalogItem } from './bus'

/** Mock：日常工具。 */
export const MOCK_DAILY: CatalogItem[] = [
  {
    id: 'wechat',
    name: '微信',
    description: '腾讯微信 PC 客户端（下载安装包并拉起安装向导）',
    group: 'daily',
    status: 'installed',
    version: '4.0',
    actions: ['install', 'uninstall'],
    uiMode: 'generic',
    tags: ['chat'],
    updateAvailable: true,
  },
  {
    id: 'sunlogin',
    name: '向日葵远程控制',
    description: '贝锐向日葵（下载安装包并拉起安装向导）',
    group: 'daily',
    status: 'missing',
    actions: ['install', 'uninstall'],
    uiMode: 'generic',
    tags: ['remote'],
    updateAvailable: false,
  },
]

/** Mock：开发工具。 */
export const MOCK_DEV: CatalogItem[] = [
  {
    id: 'volta',
    name: 'Volta',
    description: 'JavaScript 工具链版本管理器',
    group: 'dev',
    status: 'installed',
    version: '2.0.2',
    actions: ['install', 'uninstall'],
    uiMode: 'generic',
    tags: ['runtime'],
    updateAvailable: false,
  },
  {
    id: 'node',
    name: 'Node.js',
    description: '经 Volta 浏览、多选安装 / 卸载 Node，设定默认并 pin 到项目',
    group: 'dev',
    status: 'installed',
    version: '22.14.0',
    actions: ['install', 'uninstall', 'set-default', 'pin'],
    uiMode: 'panel',
    tags: ['runtime', 'needs-volta'],
    updateAvailable: false,
  },
  {
    id: 'pnpm',
    name: 'Pnpm',
    description: '经 Volta 管理 Pnpm 多版本',
    group: 'dev',
    status: 'installed',
    version: '10.6.5',
    actions: ['install', 'uninstall', 'set-default', 'pin'],
    uiMode: 'panel',
    tags: ['runtime', 'needs-volta'],
    updateAvailable: false,
  },
  {
    id: 'yarn',
    name: 'Yarn',
    description: '经 Volta 管理 Yarn 多版本',
    group: 'dev',
    status: 'missing',
    actions: ['install', 'uninstall', 'set-default', 'pin'],
    uiMode: 'panel',
    tags: ['runtime', 'needs-volta'],
    updateAvailable: false,
  },
  {
    id: 'claude-code',
    name: 'Claude Code',
    description: 'Anthropic Claude Code CLI',
    group: 'dev',
    status: 'missing',
    actions: ['install', 'uninstall', 'init'],
    uiMode: 'panel',
    tags: ['ai', 'cli'],
    updateAvailable: false,
  },
  {
    id: 'terminal-buddy',
    name: 'TerminalBuddy',
    description: '从 Gitee Release 同步安装终端',
    group: 'dev',
    status: 'installed',
    actions: ['install', 'uninstall'],
    uiMode: 'generic',
    tags: ['terminal'],
    updateAvailable: false,
  },
  {
    id: 'cc-switch',
    name: 'CC Switch',
    description: '管理 AI CLI 供应商配置',
    group: 'dev',
    status: 'missing',
    actions: ['install', 'uninstall'],
    uiMode: 'generic',
    tags: ['ai'],
    updateAvailable: false,
  },
  {
    id: 'cc-connect',
    name: 'CC Connect',
    description: '桥接 AI 助手到即时通讯',
    group: 'dev',
    status: 'missing',
    actions: ['install', 'uninstall'],
    uiMode: 'generic',
    tags: ['ai'],
    updateAvailable: false,
  },
  {
    id: 'hermes',
    name: 'Hermes Agent',
    description: 'Hermes Agent 官方 CLI',
    group: 'dev',
    status: 'missing',
    actions: ['install', 'uninstall'],
    uiMode: 'generic',
    tags: ['ai', 'cli'],
    updateAvailable: false,
  },
]
