<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Miao.Tools</RootNamespace>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Miao.Common\Miao.Common.csproj" />
    <ProjectReference Include="..\Miao.Data\Miao.Data.csproj" />
  </ItemGroup>

</Project>
